const movies = [
  {
    adult: false,
    backdrop_path: "/mExN6lJHmLeGjwDmDrNNjR4MdCq.jpg",
    genre_ids: [28, 12, 16, 35, 10751],
    id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview:
      "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 5294.537,
    poster_path: "/wYOuMSTR5D0dSwtqjYq59aqziT1.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 7.0,
    vote_count: 178,
  },
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 12, 28],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 2543.57,
    poster_path: "/sMp34cNKjIb18UBOCoAv4DpCxwY.jpg",
    release_date: "2024-03-08",
    title: "Damsel",
    video: false,
    vote_average: 7.256,
    vote_count: 930,
  },
  {
    adult: false,
    backdrop_path: "/oFAukXiMPrwLpbulGmB5suEZlrm.jpg",
    genre_ids: [28, 12, 878, 14, 18],
    id: 624091,
    original_language: "id",
    original_title: "Sri Asih",
    overview:
      "Alana discover the truth about her origin: she’s not an ordinary human being. She may be the gift for humanity and become its protector as Sri Asih. Or a destruction, if she can’t control her anger.",
    popularity: 1827.462,
    poster_path: "/wShcJSKMFg1Dy1yq7kEZuay6pLS.jpg",
    release_date: "2022-11-17",
    title: "Sri Asih",
    video: false,
    vote_average: 6.317,
    vote_count: 30,
  },
  {
    adult: false,
    backdrop_path: "/mDeUmPe4MF35WWlAqj4QFX5UauJ.jpg",
    genre_ids: [28, 27, 53],
    id: 1096197,
    original_language: "pt",
    original_title: "No Way Up",
    overview:
      "Characters from different backgrounds are thrown together when the plane they're travelling on crashes into the Pacific Ocean. A nightmare fight for survival ensues with the air supply running out and dangers creeping in from all sides.",
    popularity: 1548.682,
    poster_path: "/hu40Uxp9WtpL34jv3zyWLb5zEVY.jpg",
    release_date: "2024-01-18",
    title: "No Way Up",
    video: false,
    vote_average: 6.141,
    vote_count: 251,
  },
  {
    adult: false,
    backdrop_path: "/xvk5AhfhgQcTuaCQyq3XqAnhEma.jpg",
    genre_ids: [28, 12, 35],
    id: 848538,
    original_language: "en",
    original_title: "Argylle",
    overview:
      "When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
    popularity: 1353.29,
    poster_path: "/95VlSEfLMqeX36UVcHJuNlWEpwf.jpg",
    release_date: "2024-01-31",
    title: "Argylle",
    video: false,
    vote_average: 6.175,
    vote_count: 629,
  },
];

module.exports = { movies };
