module.exports = [
    { name: "action", emoji: "💥", label: "Acción" },
    { name: "adventure", emoji: "🤠", label: "Aventura" },
    { name: "animation", emoji: "🎬", label: "Animación" },
    { name: "comedy", emoji: "😂", label: "Comedia" },
    { name: "crime", emoji: "🔫", label: "Crimen" },
    { name: "documentary", emoji: "📽️", label: "Documental" },
    { name: "drama", emoji: "🎭", label: "Drama" },
    { name: "family", emoji: "👦", label: "Familia" },
    { name: "fantasy", emoji: "🔮", label: "Fantasía" },
    { name: "history", emoji: "📜", label: "Historia" },
    { name: "horror", emoji: "👻", label: "Terror" },
    { name: "music", emoji: "🎵", label: "Música" },
    { name: "mystery", emoji: "🕵️‍♂️", label: "Misterio" },
    { name: "romance", emoji: "❤️", label: "Romance" },
    { name: "science fiction", emoji: "🚀", label: "Ciencia Ficción" },
    { name: "tv movie", emoji: "📺", label: "Película de TV" },
    { name: "thriller", emoji: "🔪", label: "Thriller" },
    { name: "war", emoji: "🪖", label: "Guerra" },
    { name: "western", emoji: "🤠", label: "Western" }
];
